// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYaCPHwP2jw-r1tS4nlojXe85EXRqRQqQ',
    appId: '1:414239312964:web:8a765f7fbd6daed62dc011',
    messagingSenderId: '414239312964',
    projectId: 'khaled-store-3c4a5',
    authDomain: 'khaled-store-3c4a5.firebaseapp.com',
    storageBucket: 'khaled-store-3c4a5.appspot.com',
    measurementId: 'G-DKXLL3K863',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6Rwq1OPfOqJIMyQ7_VqaVE35k90kVcLw',
    appId: '1:414239312964:android:d6365d32f02a0c1b2dc011',
    messagingSenderId: '414239312964',
    projectId: 'khaled-store-3c4a5',
    storageBucket: 'khaled-store-3c4a5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4nG3TewpkdjkwDdbJlqYoOdupXAQJi6Y',
    appId: '1:414239312964:ios:132c3683020e225a2dc011',
    messagingSenderId: '414239312964',
    projectId: 'khaled-store-3c4a5',
    storageBucket: 'khaled-store-3c4a5.appspot.com',
    iosBundleId: 'com.example.khaledStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYaCPHwP2jw-r1tS4nlojXe85EXRqRQqQ',
    appId: '1:414239312964:web:f0c9c3ebe86af09c2dc011',
    messagingSenderId: '414239312964',
    projectId: 'khaled-store-3c4a5',
    authDomain: 'khaled-store-3c4a5.firebaseapp.com',
    storageBucket: 'khaled-store-3c4a5.appspot.com',
    measurementId: 'G-FWWNJ6DD04',
  );
}
